### ISSUE TITLE
ChatGPT Domain Name Changed

### ISSUE THREAD

**Issue by malekinho8** [LucasAschenbach/prompster#10]
Hi, I think the domain name of ChatGPT changed from chat.openai.com to chatgpt.com, so the "/" input no longer works. Would this be an easy fix?

**Comment by LucasAschenbach** [comment]
Thanks for reporting! This is already fixed in the latest version https://github.com/LucasAschenbach/prompster/releases/tag/v1.4.5

**Comment by malekinho8** [comment]
Thanks! :)
