### ISSUE TITLE
Slash command triggered in every position of the text field

### ISSUE THREAD

**Issue by fsp22** [LucasAschenbach/prompster#11]
When a / char is typed, prompter is activated, and it is not possible to insert the slash char (e.g., for path 'example/path/1').

Can the prompter trigger only at the beginning of the input text field?

**Comment by LucasAschenbach** [comment]
Prompster already supports this but it's a bit hidden in the settings. When clicking on the prompster icon to open your prompt library, there are three dots next to the search bar. These lead you to the settings page where you can enable "Only activate at beginning of input".

**Comment by LucasAschenbach** [comment]
Also note, when pressing backspace after prompster has been triggered, prompster will close and re-insert the '/' character.

**Comment by fsp22** [comment]
thanks
