### ISSUE TITLE
Multiline variables

### ISSUE THREAD

**Issue by infiniumparty** [LucasAschenbach/prompster#4]
Hello! If possible, please add support for multiline variables to facilitate pasting code and large texts. Currently, code and large texts lose new lines when pasted in as a variable.

Also, the "What's New" button does not work for me. It only opens a popup.html in a new tab. I found out about variables (which is a very useful functionality) very randomly. Tried on Edge and Chrome.

Thank you!

**Comment by LucasAschenbach** [comment]
Thank's for the feedback!

I'm working on an implementation that wraps the input with the text so one can use linebreaks and also see the entire content.

There is currently a website in the works for a changelog and feature list. I added a small disclaimer, hinting at the variable feature in the prompt editor for now.

**Comment by LucasAschenbach** [comment]
I just published version 1.3.3 which adds multiline variables. I expect the new version to be available within the next week.
