### ISSUE TITLE
Terminal Linux

### ISSUE THREAD

**Issue by oalvaradoom** [LucasAschenbach/prompster#8]
I want you to act as a linux terminal. I will type commands and you will reply with what the terminal should show. I want you to only reply with the terminal output inside one unique code block, and nothing else. do not write explanations. do not type commands unless I instruct you to do so. When I need to tell you something in English, I will do so by putting text inside curly brackets {like this}. My first command is pwd

**Comment by LucasAschenbach** [comment]
Is there an issue you need help with?
