### ISSUE TITLE
The slash command doesn't trigger anymore the 'Prompster' interface in Chatgpt. Is it normal?

### ISSUE THREAD

**Issue by marciobila94** [LucasAschenbach/prompster#9]
The slash command doesn't trigger anymore the 'Prompster' interface in Chatgpt. Is it normal?

**Comment by LucasAschenbach** [comment]
Thanks for reporting! The URL of ChatGPT changed which required a change in the extension's manifest. I already deployed a new version which became available on the chrome webstore about an hour ago: https://chromewebstore.google.com/detail/prompster/fbagfekcjdidpmmookklbaeddgkjddml
